-- ============================================================
--  Migration 05 — AI CV Scoring columns
--  Run once against your Supabase project.
--  Depends on: 01_schema.sql (talent_applications table)
-- ============================================================

-- ── New columns on talent_applications ──────────────────────

ALTER TABLE public.talent_applications
  ADD COLUMN IF NOT EXISTS cv_score_status TEXT
    NOT NULL DEFAULT 'pending'
    CHECK (cv_score_status IN ('pending','processing','completed','failed','no_cv')),

  ADD COLUMN IF NOT EXISTS cv_score SMALLINT
    CHECK (cv_score IS NULL OR (cv_score >= 0 AND cv_score <= 100)),

  -- Stores per-category scores + rationales as JSON, e.g.:
  -- {
  --   "skills_match":          { "score": 82, "rationale": "..." },
  --   "experience_fit":        { "score": 75, "rationale": "..." },
  --   "education_relevance":   { "score": 60, "rationale": "..." },
  --   "communication_quality": { "score": 88, "rationale": "..." }
  -- }
  ADD COLUMN IF NOT EXISTS cv_score_breakdown JSONB,

  -- 2-3 sentence human-readable summary produced by the AI
  ADD COLUMN IF NOT EXISTS cv_ai_summary TEXT,

  ADD COLUMN IF NOT EXISTS cv_parsed_at TIMESTAMPTZ;

COMMENT ON COLUMN public.talent_applications.cv_score_status IS
  'Lifecycle of the AI scoring job: pending → processing → completed | failed | no_cv';
COMMENT ON COLUMN public.talent_applications.cv_score IS
  '0-100 overall fit score generated by the AI parser';
COMMENT ON COLUMN public.talent_applications.cv_score_breakdown IS
  'JSON object with per-category scores (skills_match, experience_fit, education_relevance, communication_quality) each containing score (0-100) and rationale string';
COMMENT ON COLUMN public.talent_applications.cv_ai_summary IS
  'AI-generated 2-3 sentence candidate summary for internal review';
COMMENT ON COLUMN public.talent_applications.cv_parsed_at IS
  'Timestamp when the AI scoring completed successfully';

-- ── RLS additions ────────────────────────────────────────────

-- Service-role can update the AI columns (Edge Function uses service-role key)
-- No additional policy needed — service-role bypasses RLS by default.

-- Anon read policy: applicants can check cv_score_status on their own row
-- using their application id (passed back after insert).
-- The actual score is NOT exposed to anon users yet (premium paywall phase 2).
-- This policy grants read on the status column only via a narrow view.

-- Create a secure view so anonymous users can poll their scoring status
-- without being able to read any other columns.
CREATE OR REPLACE VIEW public.cv_score_status_view
  WITH (security_invoker = true)
AS
SELECT
  id,
  cv_score_status
FROM public.talent_applications;

-- Anon can select from this view (RLS on the underlying table still applies)
GRANT SELECT ON public.cv_score_status_view TO anon;

-- ── Index for quick admin queries by score ───────────────────
CREATE INDEX IF NOT EXISTS idx_talent_applications_cv_score
  ON public.talent_applications (cv_score DESC NULLS LAST)
  WHERE cv_score_status = 'completed';
